print('soy un cotrolador')
print('soy un cotrolador')
print('soy un cotrolador')
print('soy un cotrolador')
print('soy un cotrolador')
print('soy un cotrolador')
print('soy un cotrolador')
print('soy un cotrolador')
